blank_issues_enabled: true
contact_links:
  - name: FreeAPI Discord Server
    url: https://hitesh.ai/discord
    about: Please ask and answer questions related to FreeAPI here.
  - name: Learn FreeAPI here
    url: https://www.youtube.com/playlist?list=PLRAV69dS1uWSx4erHGq8hW_GE-Eaj60r-
    about: Gain comprehensive knowledge of FreeAPI through this curated playlist.